spring:
  application:
    name: madp-user-local
  
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/madp_user_db?serverTimezone=UTC&characterEncoding=UTF-8}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    defer-datasource-initialization: true